### PR TITLE
Support for uploading of large files

### PR DESCRIPTION
**Pull request by wiktorn**
Support for uploading large files to OneDrive.
- Added FileSlice class that provides a chunked view over file object
- Added UploadedFragment class that represents chunk upload response
- Added ability to send file like objects in RequestBase.send(...)
- Added support in ItemRequestBuilder.upload(...) to adapt it's behaviour based on file size. If file size is larger than 100MB, an upload session is used to upload files in 10MB chunks

### CODE REVIEW

**Comment by cdmayer** [comment]
Thanks for submitting this! I'm going to review it early in January.

**Comment by wiktorn** [comment]
Sounds good. I did notice that files are marked with "This file was generated and any changes will be overwritten.", though I haven't found the code generators, hence - such pull request.

If there is better way to contribute code, please let me know. I'd like also to improve documentation side of the SDK, but I hope this will be more straightforward.

**Comment by cdmayer** [comment]
I took a closer look. Can you give me an example of how you would use this code, and why you think it's the best way to get the job done? I ask because I can't see the use case. If you take a look at the [API docs](https://dev.onedrive.com/items/upload_large_files.htm) for the session-based upload, you'll see that 'item' is required anyways, so there's no reason to make it optional. Thanks!

**Comment by cdmayer** [comment]
I should have done this step earlier, but in order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.microsoft.com.

**Comment by cdmayer** [comment]
Thanks for signing that! We should be all set.

As it stands, this pull request doesn't quite fit with our design. The good news is that most of the code you wrote will not need any changes, and the bulk of changes will be moving things around. Here are the things that need to change. 
- Generally speaking, things in _/model_ and _/python{2/3}/request_ should not change, except perhaps bugfixes. These are generated from the [metadata document](https://api.onedrive.com/v1.0/$metadata), so they aren't intended to do much more than wrap OData in Python objects. Business logic should end up in modules in the root directory (just like _request_base.py_), _/extensions_, or sometimes _/helpers_.
- UploadFragment is actually a duplicate of [UploadSession](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/model/upload_session.py). You should be using that instead.
- In _item_content_request.py_ you try to be smart about using either a standard `PUT` request or a chunked upload. I like the intent, but as I mentioned above that file is autogenerated and shouldn't have business logic. Instead, I think the best approach is to create an extension class that will do the same thing. Take a look at how we did it in _[drive_request_builder_helper.py](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/extensions/drive_request_builder_helper.py)_: we use monkey patching to add `DriveRequestBuilder.item_by_path` to the auto-generated class. I recommend creating a new extension class which defines a `fragment_upload()` method and patches it onto `ItemRequestBuilder`.
- Also in _item_content_request.py_, you have this snippet:

``` python
for i in range(math.ceil(file_size / __PART_SIZE)):
    resp = upload_builder.post(i * __PART_SIZE, __PART_SIZE)
```

This swallows the results of the each individual request. It would be good to get the results for all these requests, especially since one other than the last one might fail.
- Ideally, you would execute fragment upload requests in parallel.
- Your test code should not be in the _file_slice.py_ file, but instead in the _[/testonedrivesdk](https://github.com/OneDrive/onedrive-sdk-python/tree/master/testonedrivesdk)_ directory.

I know this seems like a ton of stuff, but I think that when you refactor the code you'll be surprised at how clean it is, and how much of what you write is still usable. I really love that you are taking this on, as it's really not an easy part of the SDK. Let me know if you have any questions about my review.

Thanks!
Chris

**Comment by cdmayer** [comment]
One last thing: please use _git rebase fragment-upload_ to move your changes to the branch I just created for you. This will allow us to pull in smaller pull requests one at a time.

**Comment by wiktorn** [comment]
Ok, just to clear few things out:
- move all the code under onedrivesdk/*
- create an extension, that will create fragment_upload in ItemRequestBuilder, though with it robustness, I see plain upload(...) as not really useful
- move file_slice tests to testonedrivesdk
- use UploadSession as a response to fragment_upload

I do swallow intermediary responses, as I do feel, that they are of no use to end-user, as they only contain information, how to proceed with upload. And if they will badly fail, an exception will be thrown anyway. So for the end user, only commit response is important, because it means - that everything went fine.

Parallel upload might complicate things a lot here and I'd leave it for future improvements.

And finally - rebase to fragment-upload, what would you like to have in the end:
- pull request on fragment-upload branch with one commit containing final version of the patch
- pull request on fragment-upload branch with few meaningful commits without "hack-and-try" commits?
- split this patch to few separate pull requests?

**Comment by cdmayer** [comment]
> move all the code under onedrivesdk/*

Yes, into files in that directory.

> create an extension, that will create fragment_upload in ItemRequestBuilder, though with it robustness, I see plain upload(...) as not really useful

Yes that's correct. It's not ideal, but at the same time we have to separate the code between the auto-generated code and the manually-written code, so this is the compromise we have to make.

> move file_slice tests to testonedrivesdk

Yes!

> use UploadSession as a response to fragment_upload

`fragment_upload` should take an instance of `UploadSession` as one of its parameters, and use that instance's information (such as `upload_url`) in the implementation of `fragment_upload`.

Swallowing responses: If nothing else, those responses could be used to indicate upload progress to the user.

Parallel upload: fair enough.

Rebasing: Ideally multiple pull requests with functionality that stands on its own. For example, I think you could submit a pull request containing just the `FileSlice` class as it is useful on its own. That way, if someone else wants to chime in they can pick up the stuff you've already written.

**Comment by wiktorn** [comment]
Ok, so I created the separate Pull Request #14, but as both commits were made to fragment_upload branch, they landed in one pull request. Lets continue discussion there.

**Pull request closed without merging**
