### PR TITLE
Catch blank results in fragment_upload

### PR DESCRIPTION
**Pull request by cdmayer**

### CODE REVIEW

**Review by gyma11 — APPROVED** [review]
Seems to work! Already uploaded several large files without an error.

**Review by D4N14L — APPROVED** [review]
Looks good to me!

**Comment by ambreengames** [comment]
In my case it's now throwing this error:

Traceback (most recent call last):
  File "/root/onedrivebackup/onedrivebackup.py", line 171, in <module>
    put(sys.argv[3],parse_path(sys.argv[4]))
  File "/root/onedrivebackup/onedrivebackup.py", line 138, in put
    client.item(drive="me",path=appfolderpath+remote_file).upload_async(local_file)
  File "/usr/lib/python3.4/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 171, in fragment_upload_async
    resp = upload_builder.post(i \* **PART_SIZE, length)
  File "/usr/lib/python3.4/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 119, in post
    return self.request(begin, length, options).post()
  File "/usr/lib/python3.4/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 57, in post
    entity = UploadSession(json.loads(self.send(data=self._file_handle).content))
  File "/usr/lib/python3.4/site-packages/onedrivesdk/request_base.py", line 151, in send
    data=data)
  File "/usr/lib/python3.4/site-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/lib/python3.4/site-packages/onedrivesdk/http_response.py", line 56, in __init**
    raise OneDriveError("Invalid or empty HttpResponseBody", self.status)
  File "/usr/lib/python3.4/site-packages/onedrivesdk/error.py", line 39, in **init**
    prop_dict["code"] = ErrorCode.Malformed.value
AttributeError: 'str' object has no attribute 'value'

**Comment by gyma11** [comment]
I have exactly the same error.

**Comment by cdmayer** [comment]
Interesting. I see the problem. Can you please give #58 a shot? Sorry to make you be my guinea pigs, but I'm unable to get a repro myself so I need your help testing!

This might still throw OneDriveErrors, but it should give us more information about the response from the server, which should quickly get us to the root of the problem.

**Comment by ambreengames** [comment]
I'm on it and I'll follow up when I have more details.

**Pull request merged**
