### PR TITLE
Error handling updates

### PR DESCRIPTION
**Pull request by cdmayer**

### CODE REVIEW

**Comment by gyma11** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/http_response.py", line 47, in **init**
    message = json.loads(self.content)
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OneDriveUpload.py", line 59, in UploadFile
    client.item(drive="me", path=remoteFilePath).upload_async(localFilePath)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 170, in fragment_upload_async
    resp = upload_builder.post(i \* **PART_SIZE, length)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 118, in post
    return self.request(begin, length, options).post()
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 56, in post
    entity = UploadSession(json.loads(self.send(data=self._file_handle).content))
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/request_base.py", line 151, in send
    data=data)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/http_response.py", line 52, in __init**
    "code": ErrorCode.malformed,
AttributeError: type object 'ErrorCode' has no attribute 'malformed'

**Comment by cdmayer** [comment]
Try it again

**Comment by cdmayer** [comment]
You should get something like this: `onedrivesdk.error.OneDriveError: malformed - The following invalid JSON was returned:{response from API server}`

**Comment by gyma11** [comment]
Traceback (most recent call last):
  File "OneDriveUpload.py", line 59, in UploadFile
    client.item(drive="me", path=remoteFilePath).upload_async(localFilePath)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 179, in fragment_upload_async
    raise exc
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 170, in fragment_upload_async
    resp = upload_builder.post(i \* **PART_SIZE, length)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 118, in post
    return self.request(begin, length, options).post()
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 56, in post
    entity = UploadSession(json.loads(self.send(data=self._file_handle).content))
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/request_base.py", line 151, in send
    data=data)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/http_response.py", line 59, in __init**
    raise OneDriveError(message["error"], self.status)
onedrivesdk.error.OneDriveError: invalidRange - The uploaded fragment has already been received.

**Comment by cdmayer** [comment]
Progress! We should continue if the fragment has already been received. Added a new commit, try again please!

**Comment by ambreengames** [comment]
Ok, I was able to upload a few more big files after the last commit about handling for fragments already received.

Now I'm getting another error try after try in the middle of the upload of a big file:

```
Traceback (most recent call last):
  File "/root/onedrivebackup/onedrivebackup.py", line 171, in <module>
    put(sys.argv[3],parse_path(sys.argv[4]))
  File "/root/onedrivebackup/onedrivebackup.py", line 138, in put
    client.item(drive="me",path=appfolderpath+remote_file).upload_async(local_file)
  File "/usr/lib/python3.4/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 171, in fragment_upload_async
    resp = upload_builder.post(i * __PART_SIZE, length)
  File "/usr/lib/python3.4/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 119, in post
    return self.request(begin, length, options).post()
  File "/usr/lib/python3.4/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 57, in post
    entity = UploadSession(json.loads(self.send(data=self._file_handle).content))
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cdmayer** [comment]
This bug is bringing to light an issue with the way JSON is deserialized. We need to do some decent-sized updates to fix that. For now, I added a new `except` statement that will ignore blank responses (like the one you got). Please try again!

**Comment by ambreengames** [comment]
Seems to be working fine so far. Thank you very much!

**Pull request merged**
