### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by KTibow**
The docs don't include everything that's in the code, and after some poking around in the source code and with autocomplete I found some undocumented stuff that could be pretty helpful.

### CODE REVIEW

**Comment by KTibow** [comment]
Fixes #174 and fixes #148

**Comment by KTibow** [comment]
Fixes #149

**Comment by KTibow** [comment]
My fear is that @D4N14L, @wiktorn, and @mimisasouvanh have completely abandoned this OneDrive repository. Can you guys please come back? It's so out of date people even made a [fork](https://github.com/AtakamaLLC/onedrive-sdk-python). I :heart: all the work you did.

**Comment by wiktorn** [comment]
@KTibow I indeed made a largish contribution some time ago but I never was a maintainer/owner of this repo, so I can't help you on that.

**Comment by KTibow** [comment]
@wiktorn got it. Do you know where I can find other people though? I got mine from https://github.com/OneDrive/onedrive-sdk-python/graphs/contributors.
cdmayer hasn't been active on GitHub since November, 2016. D4N14L hasn't been active since March 12th, and has previously been off GitHub for half of a year.
At this point all of the people other than you are mimisasouvanh, ybizeul, and the rest only have done 1 commit.

**Comment by wiktorn** [comment]
I have no clue. Maybe it's time for community managed fork, looks like Microsoft has abandoned this repo.

**Comment by KTibow** [comment]
Do you think it would be a good idea to put the same PR to [onedrivesdk-fork](https://github.com/AtakamaLLC/onedrive-sdk-python)?

**Comment by wiktorn** [comment]
It might be good idea. Not sure, if they haven't moved on to  [AtakamaLLC/cloudsync-onedrive](https://github.com/AtakamaLLC/cloudsync-onedrive)

**Comment by KTibow** [comment]
Hmm, it says that it conforms to the [AtakamaLLC/cloudsync](https://github.com/AtakamaLLC/cloudsync) docs which I don't see. What does AtakamaLLC/cloudsync do? Syncing a folder or something?

**Comment by wiktorn** [comment]
You need to ask there

**Comment by mimisasouvanh** [comment]
Let me investigate who can own this PR.

**Comment by KTibow** [comment]
@mimisasouvanh Ooops... didn't mean to violate the CLA... I need to change some stuff.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information

**Pull request closed without merging**
