### PR TITLE
Datetime fixes, metadata catchup

### PR DESCRIPTION
**Pull request by cdmayer**

### CODE REVIEW

**Comment by aleh-rymasheuski** [comment]
Hi Chris,
did you test the branch on python2? It seems that commit f93f4bc breaks the project in two ways:
- deletion of `src/python2/request/__init__.py` makes `request` a non-module and prevents imports from it;
- deletion of `src/python2/request/one_drive_client.py` removes `OneDriveClient` class which is used elsewhere.

**Comment by cdmayer** [comment]
Rats. Thanks for catching that. Updated here and on PyPI.

**Comment by aleh-rymasheuski** [comment]
Hi Chris,
thank you for the quick response.
Looks like python2 code is broken a third time with that commit: `src/python2/request/item_request_builder.py` line 105 calls a missing `put` method of `ItemContentRequestBuilder` (the old version said `upload` instead of `put` and worked fine).
It is possible that the python3 version has the same problem, I didn't test the case.

Sorry for not posting a pull request; to make a pull request, I have to sign an agreement saying that my company gives up all its rights over the submitted code, which I have no permission to sign (and our lawyers won't sign it either).

**Comment by cdmayer** [comment]
Another good find. This was missed by my unit tests. I'll be sure to add a test that covers this so it doesn't regress again. Anyways, the change has been committed and updated in PyPI.

I appreciate your saying that; still, any input because it helps get the SDK to a better place. I am just glad you're giving me the opportunity to fix these bugs and staying patient as they get fixed!

**Pull request merged**
