### PR TITLE
Make item argument truely optional in upload create session

### PR DESCRIPTION
**Pull request by wiktorn**

### CODE REVIEW

**Comment by wiktorn** [comment]
As this is simple fix, I leave this open. This is needed for #14 to work properly.

**Comment by cdmayer** [comment]
This field is actually not intended to be optional. The API requires the `Item` field, which is why you get the `invalidRequest` error when you try to force the request without an `Item`. In the sample you gave me, you need to provide an item to `create_session`. Try the following:

``` python
item_name = "test_file"
new_item = onedrivesdk.Item({"name": item_name})
session = client.item(drive="me", path="backupy/"+item_name).create_session(new_item).post()
```

It's important that the name provided in the path and the `Item`'s name match, or the API will return an error.

It's clear that the SDK could give back clearer errors in this case. I'll log that as an issue and fix it soon. Let me know if this doesn't answer your questions.

**Comment by wiktorn** [comment]
I'm not sure, that REST API requires Item field, as with my changes, there is no error from Microsoft servers and I get successfull uploads.

I only get API errors when I use  "children" as here

``` python
session = client.item(drive="me", path="backupy").children['test_file'].create_session().post()
```

regardless if I use my patch or not. I guess also, that providing an Item to create_session() will also result in API error.

Having to provide name of the file in Item object and in path in Item seems to me a bad API design on Python SDK side. I haven't yet tested it, what changes in HTTP request sent to server if I provide the item object or not.

The onedrive API doc says:

```
To specify a non-default conflict behavior provide the item parameter in the request body with the appropriate value for the @name.conflictBehavior instance annotation.
```

So I read this, that if I don't need non-default conflict behaviour, I do not need to provide the item at all. And if I do not provide it - it works.

**Comment by wiktorn** [comment]
I've run some tests, and REST API indeed returns an error, when `name` argument in JSON document is different from the name in the path.

Though I do not understand, why providing it at all is necessary. Providing only `"@name.conflictBehavior": "rename"` part.

As the constructor of the class provides default None value for item, I'd say, that either this assignment should be dropped, or if `ItemCreateSessionRequest.__init__` should continue to not require the item object, but it should not fail few lines later.

**Comment by cdmayer** [comment]
If you take a look at the actual requests that you send and compare them to the API doc, you'll see why you get an error. If you send a request to create a session with `.children[]`, the generated request will look like this:

`https://api.onedrive.com/v1.0/drives/me/items/{resid}/children/{file_name}/upload.createSession`

This won't work because you can't use a file name in the URL unless you also use colon pathing. If you use the Python snippet I provided above, the request looks more like this:

`https://api.onedrive.com/v1.0/drives/me/root:/{path_to_file}/{file_name}:/upload.createSession`

The reason this is a little messy is because the `upload.createSession` action isn't exactly OData friendly. We decided to compromise 100% RESTfulness in favor of simpler interaction patterns. This is one place where the API design falls down a little.

**Comment by cdmayer** [comment]
I do agree with your final comment about the constructor. I think the reason we made the argument optional is that in other request types it _is_ optional. I need to take another look; we may be able to modify the generator so that the constructor argument is only optional if the API truly doesn't require it. Thanks for the feedback.

**Comment by wiktorn** [comment]
But if I read the metadata correctly:

``` xml
<Schema Namespace="upload">
  <Action Name="createSession" IsBound="true">
    <Parameter Name="bindingParameter" Type="oneDrive.item" Nullable="false"/>
    <Parameter Name="item" Type="oneDrive.chunkedUploadSessionDescriptor"/>
    <ReturnType Type="oneDrive.uploadSession" Nullable="false"/>
  </Action>
</Schema>
```

Then item parameter is optional (no `Nullable="false"`). So generator specifies in constructor, that `item` argument is optional. Only problem is, that generator produces broken code, as although parameter is optional, it tries to access it's contents, hence the exception from python library.

**Pull request closed without merging**
